name: Testing
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  Job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample: [playing-music-file, playing-music-memory]
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Compiling 
        run: |
          haxelib install hxcpp --quiet
          haxelib dev hxraudio .
          cd samples/${{matrix.sample}}
          haxe build.hxml
